function VBA_DCMgrapher_resize(f,~)

posf = get(f,'Position');

margin = .1*min([posf(4),posf(3)]);


if posf(3) < posf(4)
    dsize = posf(4)-posf(3);
    set(gca,'Position',[ ...
        margin, ...
        margin+dsize/2, ...
        posf(3)-2*margin, ...
        posf(3)-2*margin ...
        ]);
else
    dsize = posf(3)-posf(4);
    set(gca,'Position',[ ...
        margin+dsize/2, ...
        margin, ...
        posf(4)-2*margin, ...
        posf(4)-2*margin ...
        ]);
end  
    
  


VBA_DCMgrapher_resizeconnects(f);
VBA_DCMgrapher_resizenodes(f);
end